name: CI - Dev Staging
run-name: "CI - Dev Staging | ${{ github.ref }} | ${{ github.event_name}} | ${{ github.run_number }}"

on:
  push:
    branches: 
      - dev
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - 'tests/**'
      - '.gitignore'
      - 'pyproject.toml'
  pull_request:
    branches:
      - dev

env:
  PYTHON_VERSION: "3.12"
  DEV_DEPENDENCIES_TAG: ".[dev]"
  TEST_REPORTS_PATH: testing_reports/
  TEST_REPORTS_NAME: test-reports
  TEST_CASES_FOLDER_PATH: tests/
  CHECK_TESTING_MODULE: tests.checkresults
  
jobs:

  testing:
    name: Test & Check Results
    runs-on: ubuntu-latest
    env:
      TEST_REPORTS_PATH: testing_reports/
      TEST_REPORTS_NAME: test-reports
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install package with dev dependencies
        run: pip install -e "${{ env.DEV_DEPENDENCIES_TAG }}"

      - name: Run testing
        run: pytest ${{ env.TEST_CASES_FOLDER_PATH }} -v

      - name: Upload testing reports (JUnit XML/HTML, Coverage XML/HTML)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TEST_REPORTS_NAME }}
          path: ${{ env.TEST_REPORTS_PATH }}
          retention-days: 30

      - name: Check testing results (pass rate & coverage)
        run: python -m ${{ env.CHECK_TESTING_MODULE }}

  tag-run-number:
    name: Tag with Run Number
    runs-on: ubuntu-latest
    needs: testing
    permissions:
      contents: write
    env:
      TAG: dev-${{ github.run_number }}
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
        

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG="${{ env.TAG }}"
          git tag -a "$TAG" -m "dev run number: ${{ env.RUN_NUMBER }}"
          git push origin "$TAG"